### PR TITLE
Fix warnings when building sphinx

### PR DESCRIPTION
**Pull request by mikecaat**

### CODE REVIEW

**Comment by michaelpq** [comment]
In your second patch, the commit message mention pgsql, but it should be plpgsql.

**Comment by mikecaat** [comment]
Thanks for the review. I have merged them into a single commit and updated the commit messages. If you're ok, I'll apply it down to 14. BTW, this will be the first time I apply to the upstream repository directory.

**Comment by michaelpq** [comment]
> If you're ok, I'll apply it down to 14. BTW, this will be the first time I apply to the upstream repository directory.

No problem. Go ahead :)

**Comment by mikecaat** [comment]
Thanks! I've pushed it to master, PG15 and PG14 branches.

**Comment by mikecaat** [comment]
Also pushed to PG16.

**Pull request closed without merging**
