### PR TITLE
Synchronization of the core code actual for Postgres 13

### PR DESCRIPTION
**Pull request by WinterUnicorn**
Pull request for synchronization with actual postgresql core code of set_rel_pathlist and dependent functions.

### CODE REVIEW

**Comment by michaelpq** [comment]
I have looked at this patch.  From what I can see, the following routines are added:
- set_tablesample_rel_pathlist
- set_foreign_pathlist
- set_function_pathlist
- set_values_pathlist
- set_tablefunc_pathlist
Then all these subroutines are called within a new set_rel_pathlist(), which is actually *never* called. So I don't quite see what this is achieving.

Adding @horiguti @MasahikoSawada and @rjuju for confirmation.

**Comment by rjuju** [comment]
Agreed, I think it's some leftover of a previous implementation (I see it was added in a037c419, so quite a long time ago).  AFAICS all those functions are currently unused in all supported branch, so I'd rather get rid of it in all branches and update `update_copied_funcs.pl` accordingly.

**Comment by michaelpq** [comment]
> 



> Agreed, I think it's some leftover of a previous implementation (I see it was added in [a037c41](https://github.com/ossc-db/pg_hint_plan/commit/a037c4195fe3f5e07d694b0206c19f142d8369d2), so quite a long time ago). AFAICS all those functions are currently unused in all supported branch, so I'd rather get rid of it in all branches and update `update_copied_funcs.pl` accordingly.

I am not sure that it is worth touching the stable branches for any of that, but that sounds like a plan for HEAD (15~).

**Comment by michaelpq** [comment]
At the end, I have not cleaned up HEAD but I did not bother with updating the other branches. Note that the cleanup has been done after running update_copied_funcs.pl.

**Pull request closed without merging**
