### PR TITLE
Large cleanup of README file

### PR DESCRIPTION
**Pull request by xzilla**
These changes include fixing a number of typos, some syntax errors in the examples, and a fair amount of wordsmithing for clarification and/or grammar improvements.

### CODE REVIEW

**Comment by michaelpq** [comment]
Thanks for the patches. Will look into that.

**Comment by michaelpq** [comment]
I think that it would be better to squash the two commits into a single one. From what I can see, the HTML documentation in English has not been changed to reflect the changes done in README.md. Also, could it be a bit better for readability if the README is rewritten with a limit of 80-characters per line.

Feel free to discard the last point, I am old-school :)

**Comment by michaelpq** [comment]
I have opened a new ticket to discuss if the HTML documentation had better be dropped in #123. I am not really a fan in maintaining a duplication of both these things. That's just time-draining.

**Comment by xzilla** [comment]
I don't see any issues with squashing the two commits during the merge (presuming it will be merged 🙂). 

I think if you want to reformat to 80-char line limit, I wonder how that would affect the readability of the formatted tables towards the end, but I am generally indifferent about it, with my main thought being it should be part of a separate commit/patch (like a pgindent run)

**Comment by michaelpq** [comment]
@xzilla After changes like  49a8839 and 41ffa51. Do you still see areas that could be improved?

**Comment by michaelpq** [comment]
Closing for now.

**Pull request closed without merging**
